import { 
  Salon, 
  Category, 
  Service, 
  Professional, 
  Client, 
  Appointment, 
  Coupon, 
  Review, 
  WaitlistItem,
  AIInsight,
  SalonUnit,
  InventoryItem
} from '@/types';

export const initialSalon: Salon = {
  id: 'salon-1',
  name: 'Konnexy Agenda',
  slug: 'konnexy-agenda',
  logo_url: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=200&h=200&fit=crop&q=80',
  phone: '(11) 98765-4321',
  email: 'contato@konnexyagenda.com.br',
  address: 'Alameda Gabriel Monteiro da Silva, 1420 - Jardins, São Paulo - SP',
  city: 'São Paulo',
  state: 'SP',
  primary_color: '#C08497',
  accent_color: '#8B5E83',
  working_hours: {
    days: [1, 2, 3, 4, 5, 6], // Mon-Sat
    open: '08:00',
    close: '20:00',
  },
  interval_minutes: 30,
};

export const initialSalonUnits: SalonUnit[] = [
  { id: 'unit-1', name: 'Unidade Jardins (Matriz)', address: 'Alameda Gabriel Monteiro da Silva, 1420', phone: '(11) 98765-4321', is_main: true },
  { id: 'unit-2', name: 'Unidade Alphaville', address: 'Alameda Rio Negro, 500 - Barueri', phone: '(11) 97766-5544', is_main: false },
  { id: 'unit-3', name: 'Unidade Moema', address: 'Av. Moema, 340 - São Paulo', phone: '(11) 96655-4433', is_main: false },
];

export const initialInventory: InventoryItem[] = [
  { id: 'inv-1', name: 'Tintura Wella Illumina 8.69', category: 'Coloração', quantity: 3, min_quantity: 5, unit: 'tubos', cost_price: 45.00, supplier: 'Wella Professionals', status: 'low' },
  { id: 'inv-2', name: 'Shampoo Kérastase Nutritive 1L', category: 'Lavatório', quantity: 8, min_quantity: 4, unit: 'frascos', cost_price: 180.00, supplier: 'L\'Oréal Division', status: 'ok' },
  { id: 'inv-3', name: 'Proteção Olaplex N°1 & N°2', category: 'Tratamento', quantity: 2, min_quantity: 3, unit: 'kits', cost_price: 320.00, supplier: 'Olaplex Brasil', status: 'critical' },
  { id: 'inv-4', name: 'Esmalte Gel Impala Red Lux', category: 'Manicure', quantity: 15, min_quantity: 6, unit: 'frascos', cost_price: 18.00, supplier: 'Impala Cosméticos', status: 'ok' },
  { id: 'inv-5', name: 'Cera Hidratante Parafina Quente', category: 'Spa Mãos', quantity: 12, min_quantity: 5, unit: 'potes', cost_price: 28.00, supplier: 'Beauty Care', status: 'ok' },
];

export const initialCategories: Category[] = [
  { id: 'cat-1', salon_id: 'salon-1', name: 'Cabelos & Penteados', slug: 'cabelos', order: 1 },
  { id: 'cat-2', salon_id: 'salon-1', name: 'Coloração & Mechas', slug: 'coloracao', order: 2 },
  { id: 'cat-3', salon_id: 'salon-1', name: 'Estética & Facial', slug: 'estetica', order: 3 },
  { id: 'cat-4', salon_id: 'salon-1', name: 'Sobrancelhas & Cílios', slug: 'sobrancelhas', order: 4 },
  { id: 'cat-5', salon_id: 'salon-1', name: 'Unhas & Spa das Mãos', slug: 'unhas', order: 5 },
];

export const initialServices: Service[] = [
  {
    id: 'srv-1',
    salon_id: 'salon-1',
    category_id: 'cat-1',
    category_name: 'Cabelos & Penteados',
    name: 'Corte Feminino Customizado',
    slug: 'corte-feminino',
    description: 'Corte personalizado com visagismo, lavagem especial Kérastase e secagem modelada.',
    price: 180.00,
    duration_minutes: 60,
    buffer_minutes: 10,
    image_url: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=600&auto=format&fit=crop&q=80',
    color: '#C08497',
    is_active: true,
  },
  {
    id: 'srv-2',
    salon_id: 'salon-1',
    category_id: 'cat-2',
    category_name: 'Coloração & Mechas',
    name: 'Luzes & Mechas Platinum',
    slug: 'luzes-e-mechas',
    description: 'Técnica exclusiva de iluminação dos fios com proteção Olaplex, tonalização e reconstrução.',
    price: 450.00,
    duration_minutes: 180,
    buffer_minutes: 15,
    image_url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&auto=format&fit=crop&q=80',
    color: '#8B5E83',
    is_active: true,
  },
  {
    id: 'srv-3',
    salon_id: 'salon-1',
    category_id: 'cat-1',
    category_name: 'Cabelos & Penteados',
    name: 'Progressiva Orgânica Premium',
    slug: 'progressiva-organica',
    description: 'Alinhamento térmico 0% formaldeído, proporciona brilho espelhado e maciez intensa.',
    price: 320.00,
    duration_minutes: 120,
    buffer_minutes: 15,
    image_url: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=600&auto=format&fit=crop&q=80',
    color: '#C08497',
    is_active: true,
  },
  {
    id: 'srv-4',
    salon_id: 'salon-1',
    category_id: 'cat-1',
    category_name: 'Cabelos & Penteados',
    name: 'Escova Modelada com Babyliss',
    slug: 'escova-modelada',
    description: 'Higienização com xampu de nutrição, escovação e finalização com ondas babyliss duradouras.',
    price: 110.00,
    duration_minutes: 45,
    buffer_minutes: 5,
    image_url: 'https://images.unsplash.com/photo-1560869713-7d0a29430803?w=600&auto=format&fit=crop&q=80',
    color: '#D99BBA',
    is_active: true,
  },
  {
    id: 'srv-5',
    salon_id: 'salon-1',
    category_id: 'cat-3',
    category_name: 'Estética & Facial',
    name: 'Limpeza de Pele Ultrassônica',
    slug: 'limpeza-de-pele',
    description: 'Higienização profunda, extração sem dor, peeling ultrassônico e máscara de colágeno.',
    price: 220.00,
    duration_minutes: 75,
    buffer_minutes: 10,
    image_url: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&auto=format&fit=crop&q=80',
    color: '#8B5E83',
    is_active: true,
  },
  {
    id: 'srv-6',
    salon_id: 'salon-1',
    category_id: 'cat-4',
    category_name: 'Sobrancelhas & Cílios',
    name: 'Design de Sobrancelha com Henna',
    slug: 'design-sobrancelha-henna',
    description: 'Mapeamento facial visagista, alinhamento dos fios e pigmentação de alta durabilidade.',
    price: 95.00,
    duration_minutes: 45,
    buffer_minutes: 5,
    image_url: 'https://images.unsplash.com/photo-1583001809873-a1284d5630be?w=600&auto=format&fit=crop&q=80',
    color: '#C08497',
    is_active: true,
  },
  {
    id: 'srv-7',
    salon_id: 'salon-1',
    category_id: 'cat-5',
    category_name: 'Unhas & Spa das Mãos',
    name: 'Manicure & Pedicure de Luxo',
    slug: 'manicure-pedicure-luxo',
    description: 'Cutilagem russa, esmaltação em gel e esfoliação com hidratação de parafina quente.',
    price: 130.00,
    duration_minutes: 60,
    buffer_minutes: 10,
    image_url: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=600&auto=format&fit=crop&q=80',
    color: '#D99BBA',
    is_active: true,
  },
  {
    id: 'srv-8',
    salon_id: 'salon-1',
    category_id: 'cat-1',
    category_name: 'Cabelos & Penteados',
    name: 'Hidratação Profunda Kérastase',
    slug: 'hidratacao-kerastase',
    description: 'Tratamento intensivo de restauração da fibra capilar com ampolas concentradas e secagem.',
    price: 250.00,
    duration_minutes: 50,
    buffer_minutes: 10,
    image_url: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=600&auto=format&fit=crop&q=80',
    color: '#8B5E83',
    is_active: true,
  }
];

export const initialProfessionals: Professional[] = [
  {
    id: 'pro-1',
    salon_id: 'salon-1',
    name: 'Juliana Calixto',
    email: 'juliana@konnexyagenda.com.br',
    phone: '(11) 99887-1122',
    photo_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop&q=80',
    specialty: 'Master Hair Stylist & Visagista',
    description: 'Mais de 12 anos de experiência em mechas loiras, corte visagista e transformações.',
    experience_years: 12,
    instagram: '@juliana.calixto.hair',
    working_days: [1, 2, 3, 4, 5, 6],
    working_hours: { start: '08:00', end: '19:00' },
    break_hours: { start: '12:00', end: '13:00' },
    status: 'active',
    services: ['srv-1', 'srv-2', 'srv-3', 'srv-4', 'srv-8'],
    commission_rate: 45,
  },
  {
    id: 'pro-2',
    salon_id: 'salon-1',
    name: 'Camila Rodriguez',
    email: 'camila@konnexyagenda.com.br',
    phone: '(11) 99887-2233',
    photo_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&q=80',
    specialty: 'Especialista em Estética Facial & Sobrancelhas',
    description: 'Pós-graduada em cosmetologia, expert em micropigmentação e tratamentos faciais.',
    experience_years: 8,
    instagram: '@camila.estetica',
    working_days: [1, 2, 3, 4, 5],
    working_hours: { start: '09:00', end: '18:00' },
    break_hours: { start: '13:00', end: '14:00' },
    status: 'active',
    services: ['srv-5', 'srv-6'],
    commission_rate: 40,
  },
  {
    id: 'pro-3',
    salon_id: 'salon-1',
    name: 'Beatris Santos',
    email: 'beatris@konnexyagenda.com.br',
    phone: '(11) 99887-3344',
    photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&q=80',
    specialty: 'Nail Designer & Spa Specialist',
    description: 'Especialista em alongamentos de unhas em gel e nail art minimalista elegante.',
    experience_years: 6,
    instagram: '@bea.nails.design',
    working_days: [2, 3, 4, 5, 6],
    working_hours: { start: '09:00', end: '19:00' },
    break_hours: { start: '12:30', end: '13:30' },
    status: 'active',
    services: ['srv-7'],
    commission_rate: 50,
  },
  {
    id: 'pro-4',
    salon_id: 'salon-1',
    name: 'Gabriel Oliveira',
    email: 'gabriel@konnexyagenda.com.br',
    phone: '(11) 99887-4455',
    photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&q=80',
    specialty: 'Hair Colorist & Penteados',
    description: 'Especializado em escovas modeladas, tratamentos de brilho e penteados sociais.',
    experience_years: 7,
    instagram: '@gabriel.hairstylist',
    working_days: [1, 3, 4, 5, 6],
    working_hours: { start: '10:00', end: '20:00' },
    break_hours: { start: '14:00', end: '15:00' },
    status: 'active',
    services: ['srv-1', 'srv-4', 'srv-8'],
    commission_rate: 40,
  }
];

export const initialClients: Client[] = [
  {
    id: 'cli-1',
    salon_id: 'salon-1',
    name: 'Fernanda Lima',
    phone: '(11) 97123-4567',
    email: 'fernanda.lima@gmail.com',
    birthday: '1992-05-15',
    notes: 'Prefere café sem açúcar. Sensibilidade no couro cabeludo.',
    tier: 'vip_ouro',
    color_formula: 'Wella Illumina 8.69 + 20vol (40g)',
    allergies: 'Alergia a fragrâncias florais sintéticas',
    preferred_brands: 'Kérastase, Olaplex',
    total_spent: 1240.00,
    visits_count: 7,
    last_visit: '2026-07-10',
    created_at: '2026-01-15',
  },
  {
    id: 'cli-2',
    salon_id: 'salon-1',
    name: 'Mariana Mendonça',
    phone: '(11) 98234-5678',
    email: 'mariana.m@hotmail.com',
    birthday: '1988-11-20',
    notes: 'Cliente vip diamante. Gosta de fazer luzes a cada 3 meses.',
    tier: 'vip_diamante',
    color_formula: 'Igora Royal 9.7 + Blondme 9+ (30g)',
    allergies: 'Nenhuma alergia relatada',
    preferred_brands: 'Schwarzkopf Blondme',
    total_spent: 2150.00,
    visits_count: 12,
    last_visit: '2026-07-02',
    created_at: '2025-10-05',
  },
  {
    id: 'cli-3',
    salon_id: 'salon-1',
    name: 'Patricia Souza',
    phone: '(11) 99345-6789',
    email: 'patricia.souza@outlook.com',
    birthday: '1995-08-03',
    notes: 'Faz escova todas as sextas-feiras.',
    tier: 'padrao',
    color_formula: 'Sem tonalização prévia',
    allergies: 'Nenhuma',
    preferred_brands: 'L\'Oréal Professionnel',
    total_spent: 890.00,
    visits_count: 8,
    last_visit: '2026-07-18',
    created_at: '2026-03-12',
  }
];

const getTodayStr = (offsetDays = 0) => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
};

export const initialAppointments: Appointment[] = [
  {
    id: 'apt-1',
    salon_id: 'salon-1',
    client_id: 'cli-1',
    client_name: 'Fernanda Lima',
    client_phone: '(11) 97123-4567',
    client_email: 'fernanda.lima@gmail.com',
    professional_id: 'pro-1',
    professional_name: 'Juliana Calixto',
    professional_photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop&q=80',
    service_id: 'srv-1',
    service_name: 'Corte Feminino Customizado',
    service_price: 180.00,
    service_duration: 60,
    service_color: '#C08497',
    date: getTodayStr(0),
    start_time: '10:00',
    end_time: '11:00',
    price: 180.00,
    discount: 0,
    final_price: 180.00,
    status: 'confirmed',
    notes: 'Manter comprimento das pontas',
    payment_status: 'paid',
    payment_method: 'pix',
    confirmation_stage: 'confirmed',
    before_image_url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400',
    after_image_url: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=400',
    authorized_publication: true,
    created_at: getTodayStr(-1),
  },
  {
    id: 'apt-2',
    salon_id: 'salon-1',
    client_id: 'cli-2',
    client_name: 'Mariana Mendonça',
    client_phone: '(11) 98234-5678',
    client_email: 'mariana.m@hotmail.com',
    professional_id: 'pro-1',
    professional_name: 'Juliana Calixto',
    professional_photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop&q=80',
    service_id: 'srv-2',
    service_name: 'Luzes & Mechas Platinum',
    service_price: 450.00,
    service_duration: 180,
    service_color: '#8B5E83',
    date: getTodayStr(0),
    start_time: '14:00',
    end_time: '17:00',
    price: 450.00,
    discount: 45.00,
    final_price: 405.00,
    status: 'scheduled',
    notes: 'Usou cupom BELEZA10',
    payment_status: 'pending',
    confirmation_stage: '24h',
    created_at: getTodayStr(-2),
  },
  {
    id: 'apt-3',
    salon_id: 'salon-1',
    client_id: 'cli-3',
    client_name: 'Patricia Souza',
    client_phone: '(11) 99345-6789',
    client_email: 'patricia.souza@outlook.com',
    professional_id: 'pro-2',
    professional_name: 'Camila Rodriguez',
    professional_photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&q=80',
    service_id: 'srv-5',
    service_name: 'Limpeza de Pele Ultrassônica',
    service_price: 220.00,
    service_duration: 75,
    service_color: '#8B5E83',
    date: getTodayStr(1),
    start_time: '11:00',
    end_time: '12:15',
    price: 220.00,
    discount: 0,
    final_price: 220.00,
    status: 'scheduled',
    payment_status: 'pending',
    confirmation_stage: '48h',
    created_at: getTodayStr(0),
  }
];

export const initialCoupons: Coupon[] = [
  {
    id: 'coup-1',
    salon_id: 'salon-1',
    code: 'PRIMEIRA10',
    discount_type: 'percentage',
    discount_value: 10,
    min_spend: 100,
    used_count: 24,
    is_active: true,
  },
  {
    id: 'coup-2',
    salon_id: 'salon-1',
    code: 'VIP50',
    discount_type: 'fixed',
    discount_value: 50,
    min_spend: 300,
    used_count: 8,
    is_active: true,
  }
];

export const initialReviews: Review[] = [
  {
    id: 'rev-1',
    appointment_id: 'apt-101',
    client_name: 'Clarissa Aguiar',
    professional_name: 'Juliana Calixto',
    service_name: 'Corte Feminino Customizado',
    rating: 5,
    comment: 'Atendimento impecável! O corte ficou exatamente como eu queria. O salão é divino e super cheiroso.',
    is_featured: true,
    created_at: '2026-07-20',
  },
  {
    id: 'rev-2',
    appointment_id: 'apt-102',
    client_name: 'Renata Vasconcelos',
    professional_name: 'Camila Rodriguez',
    service_name: 'Limpeza de Pele Ultrassônica',
    rating: 5,
    comment: 'Minha pele nunca ficou tão iluminada e macia. A Camila é de uma delicadeza absurda!',
    is_featured: true,
    created_at: '2026-07-22',
  },
  {
    id: 'rev-3',
    appointment_id: 'apt-103',
    client_name: 'Sofia Alencar',
    professional_name: 'Beatris Santos',
    service_name: 'Manicure & Pedicure de Luxo',
    rating: 5,
    comment: 'Unhas perfeitas! A cutilagem russa dura semanas. Recomendo de olhos fechados.',
    is_featured: true,
    created_at: '2026-07-23',
  }
];

export const initialAIInsights: AIInsight[] = [
  {
    id: 'ai-1',
    title: 'Melhor Horário para Abertura de Agenda',
    category: 'occupancy',
    insight: 'Análise de 6 meses de dados indica que as quintas-feiras às 18h00 possuem 97% de ocupação histórica.',
    suggestion: 'Abrir horários extras de encaixe com 15% de sobretaxa ou criar pacotes expressos de fim de tarde.',
    metric: '97% Taxa de Ocupação'
  },
  {
    id: 'ai-2',
    title: 'Previsão de Retorno de Clientes',
    category: 'retention',
    insight: 'Clientes que realizaram Progressiva Orgânica tendem a retornar ao salão em média a cada 92 dias.',
    suggestion: 'Enviar notificação automática de lembrete de retoque de raiz 80 dias após o procedimento.',
    metric: 'Retorno médio: 92 dias'
  },
  {
    id: 'ai-3',
    title: 'Otimização de Faturamento nas Terças-Feiras',
    category: 'marketing',
    insight: 'Terça-feira é o dia com menor taxa de agendamento (38% de ocupação).',
    suggestion: 'Lançar a promoção "Terça-Feira da Hidratação" com 15% de desconto para preencher a agenda da equipe.',
    metric: '38% Ocupação Atual'
  }
];
